feat: create board list paging
kokoa2021/aca.it pull request #11
Opened 2021-05-30 16:37 UTC by SangWook94Kokoa

<feat>
- CriteriaVO : 페이징 쿼리 동적제어에 필요한 데이터 'pageNum'과 'amount'을 관리
- PageMakerVO : 페이지번호, 이전페이지, 다음페이지, 현재페이지 정보 관리

<chore>
- boardVO 변수명 수정

2021-05-31 00:13 UTC, suyeonkwon requested changes
드디어 button의 첫 PR.. 리뷰할수있게 되어서 매우 HAPPY 🤩
수정이 필요한 line 밑에 comment를 달아 두었음!
아래는 모든 코드들에 대한 공통 수정사항 

## 공통 수정 사항
1. 사용하지 않는 코드는 주석처리 X 삭제
2. 코드의 들여쓰기 LEVEL 맞추기
- 들여쓰기만 잘해줘도 코드 가독성이 좋아진다
- java, jsp, xml 모두 해당
3. 변수명은 소문자로 시작한다
- 자바 명명 규칙은 카멜 케이스를 따른다

---
gitignore 파일이 적용이 안되는거 같다...!! 다시 확인하고 올릴테니까 그 전까지
* .classpath 
* .settings
* root-context.xml 
파일들은 commit 칠때 제외하고 올려주길 바랍니당

2021-05-31 13:33 UTC, SangWook94Kokoa commented on src/main/webapp/WEB-INF/views/board/board.jsp
> +			</div>
넵

2021-05-31 13:34 UTC, SangWook94Kokoa commented on src/main/webapp/WEB-INF/views/board/board.jsp
> +		    });
해볼게요

2021-05-31 13:35 UTC, SangWook94Kokoa commented on src/main/webapp/WEB-INF/views/main.jsp
> +          <a href="/acait/board">게시물 목록</a>
넵!

2021-05-31 13:36 UTC, SangWook94Kokoa commented on target/classes/mapper/BoardMapper.xml
> +        select count(*) from tb_board
SELECT COUNT(*) FROM TB_BOARD 이렇게요?

2021-05-31 13:41 UTC, suyeonkwon commented on target/classes/mapper/BoardMapper.xml
> +        select count(*) from tb_board
정답이에요
참 잘했어요~~~~👍

2021-06-06 23:42 UTC, suyeonkwon approved these changes
코멘트 달아놓은 부분 확인해서 다음 PR때 수정해주세요!
일단은 큰 오류가 없기 때문에 develop branch에 merge 하겠습니다
그리고 ⛏관련없는, 삭제해야하는, 삭제됐어야⛏하는 파일들은
❌절대❌❌절대❌ ❌절대❌ ❌절대❌ ❌절대❌ 
 커밋치지 않아요

2021-06-06 23:42 UTC, suyeonkwon commented on src/main/webapp/WEB-INF/views/board/board.jsp
> +	</style>
style관련 코드들은 jsp 파일에 바로 작성하지 말고
aca.it/src/main/webapp/resources/css/
해당 경로 밑에 css 파일로 생성하여서 
aca.it/src/main/webapp/WEB-INF/views/tiles/css.jsp에
stylesheet link 추가 후 사용해주세요!

2021-06-06 23:44 UTC, merged